config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :kegs do
    resources :pulls
  end
  
  namespace :api do 
    namespace :v1 do 
        resources :draws
      end 
  end 
end

app/models/api/v1.rb
module Api::V1
  def self.table_name_prefix
    'api_v1_'
  end
end

app/models/api/v1/draw.rb
class Api::V1::Draw < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/keg.rb
class Keg < ApplicationRecord
  has_many:pulls, dependent: :destroy
  validates :brand, presence:true
  validates :name, presence:true
  validates :amount, presence:true
end

app/models/pull.rb
class Pull < ApplicationRecord
  belongs_to :keg
end

app/controllers/api/v1/draws_controller.rb
class Api::V1::DrawsController < ApplicationController
    def index
    	@drawer = Draw.all
        render json: {status: 'SUCCESS', message: 'Loaded all draws', data: @drawer}, status: :ok
    end 

    def new
		@drawer = Draw.new(draw_params)
        render json: {status: 'SUCCESS', message: 'Loaded all draws', data: "draws"}, status: :ok
	end

	def create
		@draw = Draw.new(draw_params)

		if @draw.save
			redirect_to @draw
		else
			render 'new'
		end
	end

    def show
        draws = Draw.all
        render json: {status: 'SUCCESS', message: 'Loaded draw', data: draws}, status: :ok
    end



    private
    def draw_params
        params.require(:draw).permit(:amount)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/kegs_controller.rb
class KegsController < ApplicationController

    def index
        @kegs = Keg.all
    end

    def new
        @keg = Keg.new
    end

    def edit
      @keg = Keg.find(params[:id])
    end
    def update 
        @keg = Keg.find(params[:id])
    
      if @keg.update(keg_params)
        redirect_to @keg
      else
        render 'edit'
      end
    end

    def create
      @keg = Keg.new(keg_params)

      if @keg.save
        redirect_to @keg
      else
        render 'new'
      end
    end

    def show
      @keg = Keg.find(params[:id])
    end

    def destroy
      @keg = Keg.find(params[:id])

      @keg.destroy

      redirect_to kegs_path  
    end
private
  def keg_params
    params.require(:keg).permit(:brand, :name, :amount)
  end

end

app/controllers/pulls_controller.rb
class PullsController < ApplicationController
  def create
    @keg = Keg.find(params[:keg_id])
    @pull = @keg.pulls.create(pull_params)
    redirect_to keg_path(@keg)
  end

  def destroy
    @keg = Keg.find(params[:keg_id])
    @pull = @keg.pulls.find(params[:id])
    @pull.destroy
    redirect_to keg_path(@keg)
  end
  private
    def pull_params
      params.require(:pull).permit(:amount)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/draws_helper.rb
module DrawsHelper
end

app/helpers/kegs_helper.rb
module KegsHelper
end

app/helpers/pulls_helper.rb
module PullsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/kegs/_form.html.erb
<%= form_for @keg do |f| %>
 
  <% if @keg.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@keg.errors.count, "error") %> prohibited
        this keg from being saved:
      </h2>
      <ul>
        <% @keg.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :brand %><br>
    <%= f.text_field :brand %> 
  </p>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <%= f.label :amount %><br>
    <%= f.text_field :amount%>
  </p>
  <p>
    <%= f.submit%>
  </p>
 
<% end %>

app/views/kegs/edit.html.erb
<h1>Editing keg</h1>
 
<%= render 'form' %> 

 
<%= link_to 'Back', kegs_path %>

app/views/kegs/index.html.erb
<h1>Listing Kegs</h1>
 
<%= link_to 'Add new keg', new_keg_path%>
<table>
  <tr>
    <th>Brand</th>
    <th>Name</th>
    <th>Amount</th>
  </tr>
 
  <% @kegs.each do |keg| %>
    <tr>
      <td><%= keg.brand %></td>
      <td><%= keg.name %></td>
      <td><%= keg.amount %></td>
      <td><%= link_to 'Show', keg_path(keg) %></td>
      <td><%= link_to 'Edit', edit_keg_path(keg) %></td>
      <td><%= link_to 'Destroy', keg_path(keg),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/kegs/new.html.erb
<h1>New Keg</h1>


<%= render 'form'%>

<%= link_to 'Back', kegs_path%>

app/views/kegs/show.html.erb
<p>
    Brand:
    <%= @keg.brand %> 
  </p>

  <p>
    Name:
    <%= @keg.name %>
  </p>

  <p>
    Amount:
    <%= @keg.amount%>
  </p>

  <h2>Pulls: </h2>
  <%= render @keg.pulls %>

  <h2>Add Pull:</h2>
  <%= render 'pulls/form'%>



  <%= link_to 'Edit', edit_keg_path%>
  <%= link_to 'Back', kegs_path%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JustOneMore2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pulls/_form.html.erb
<%= form_for([@keg, @keg.pulls.build]) do |f| %>
    <p>
      <%= f.label :amount %>
      <%= f.text_field :amount %>
    </p>
    <p>
      <%= f.submit %>
    </p>
  <% end %>

app/views/pulls/_pull.html.erb
    <p>
      Amount:
      <%= pull.amount %>
    </p>
    <p>
      <%= link_to 'destroy pull', [pull.keg, pull],
                  method: :delete,
                  data: {confirm: 'Are you sure?'} %>
    </p>

app/views/welcome/index.html.erb
<h1>Welcome!!!</h1>
<%= link_to 'My kegs', controller: 'kegs' %>
<%= link_to 'New Keg', new_keg_path %>